services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: odoo_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - odoo_network

  # Odoo Application
  odoo:
    image: odoo:17.0
    container_name: odoo_app
    depends_on:
      - postgres
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo_password
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
    ports:
      - "8069:8069"
    networks:
      - odoo_network
    command: --
      --dev=reload,qweb,werkzeug,xml

volumes:
  postgres_data:
  odoo_data:

networks:
  odoo_network:
    driver: bridge